### ISSUE TITLE
OS X High Sierra <Control-a> and <Key-Home> behaviour

### ISSUE THREAD

**Issue by jhjl** [wjoye/tkcon#1]
On Mac OS X High Sierra, in TkCon 2.7, pressing Home or Control-a is positioning the curser at the start of the prompt rather than the after it. This seems to be due to a <<LineStart>> binding inherited from the underlying Text widget. As a workaround I have added the following which fixes this issue for me:

_In tkcon.tcl at line 5106, insert_

     if {$PRIV(AQUA)} {
         bind TkConsole <<LineStart>> {tk::TextSetCursor %W limit}
     }

**Comment by wjoye** [comment]
done. Thanks!
